# Generated by Django 2.2.3 on 2019-08-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('city', models.CharField(blank=True, choices=[('الانبار', 'الانبار'), ('البصره', 'البصره'), ('المثنى', 'المثنى'), ('القادسيه', 'القادسيه'), ('النجف', 'النجف'), ('اربيل', 'اربيل'), ('سليمانية', 'سليمانية'), ('بابل', 'بابل'), ('بغداد', 'بغداد'), ('دهوك', 'دهوك'), ('ذي قار', 'ذي قار'), ('ديالى', 'ديالى'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('ميسان', 'ميسان'), ('نينوى', 'نينوى'), ('صلاح الدين', 'صلاح الدين'), ('واسط', 'واسط')], max_length=50)),
                ('note', models.TextField(max_length=150)),
                ('specialization', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
