# Generated by Django 2.2.3 on 2019-08-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'ordering': ('full_name',)},
        ),
        migrations.AlterField(
            model_name='cv',
            name='city',
            field=models.CharField(choices=[('بغداد', 'بغداد'), ('سليمانية', 'سليمانية'), ('الانبار', 'الانبار'), ('كربلاء', 'كربلاء'), ('كركوك', 'كركوك'), ('نينوى', 'نينوى'), ('اربيل', 'اربيل'), ('البصره', 'البصره'), ('واسط', 'واسط'), ('بابل', 'بابل'), ('ديالى', 'ديالى')], max_length=50),
        ),
    ]
