# Generated by Django 2.2.3 on 2019-08-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190814_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
